"""Secure multi-client subagent distribution models and orchestration."""

from .compatibility import (
    ClientCompatibility,
    CompatibilityResult,
    load_compatibility_matrix,
    validate_client_compatibility,
)
from .models import (
    BackupSpec,
    BlockAction,
    DesiredFile,
    FileAction,
    GlobalInstructionSpec,
    IdentityEvidence,
    LifecycleAction,
    ManagedBlockSpec,
    Request,
    SourceSpec,
    Target,
    TargetCapability,
    TargetDescriptor,
    TargetProfileDefaults,
    decode_lifecycle_action,
)
from .targets import (
    CAPABILITIES,
    capability_for,
    parser_for,
    runtime_sources_for,
    semantic_validator_for,
    targets_for_request,
)

__all__ = [
    "CAPABILITIES",
    "BackupSpec",
    "BlockAction",
    "ClientCompatibility",
    "CompatibilityResult",
    "DesiredFile",
    "FileAction",
    "GlobalInstructionSpec",
    "IdentityEvidence",
    "LifecycleAction",
    "ManagedBlockSpec",
    "Request",
    "SourceSpec",
    "Target",
    "TargetCapability",
    "TargetDescriptor",
    "TargetProfileDefaults",
    "capability_for",
    "decode_lifecycle_action",
    "load_compatibility_matrix",
    "parser_for",
    "runtime_sources_for",
    "semantic_validator_for",
    "targets_for_request",
    "validate_client_compatibility",
]
